const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url'),assert=require('assert');
const {chromium}=require(process.env.C0_PLAYWRIGHT || 'playwright');
(async()=>{
 const output=path.resolve('NihongoLife/Docs/AssetPipeline/Reports/StageC0BrowserQA');fs.mkdirSync(output,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));
 const check=(name,value)=>{assert(value,name);checks.push(name)};
 await page.goto(pathToFileURL(path.resolve('NihongoLife/Docs/AssetPipeline/Preview/index.html')).href);
 const loaded=await page.evaluate(async()=>{const rows=NIHONGO_ASSETS.entries.filter(r=>r.imageUrl);const results=await Promise.all(rows.map(r=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i.naturalWidth===512);i.onerror=()=>resolve(false);i.src=r.imageUrl})));return results.filter(Boolean).length});
 check('All 438 actual PNG URLs load from file://',loaded===438);
 await page.evaluate(async()=>{await Promise.all([...document.querySelectorAll('#hero-icons img')].map(i=>i.decode()))});
 check('40 cards per first page',await page.locator('.asset-card').count()===40);
 await page.screenshot({path:path.join(output,'desktop-gallery.png')});
 let count=0;for(let i=0;i<11;i++){count+=await page.locator('.asset-card').count();if(i<10)await page.click('#next-page')};check('Pagination covers 438 gallery cards',count===438);
 await page.click('[data-category="Fashion"]');check('Fashion has honest empty state',await page.locator('.asset-card').count()===0);
 await page.click('[data-category="All"]');await page.fill('#search','no-such-item-9988');check('Zero-result search',await page.locator('.asset-card').count()===0);
 await page.fill('#search','food_apple');check('Search source identity',await page.locator('.asset-card').count()===1);
 await page.click('[data-inspect]');check('Detail semantic warning present',(await page.locator('#dialog-content').innerText()).includes('Semantic mismatch'));
 await page.click('[data-copy="source"]');await page.waitForTimeout(150);check('Copy path feedback',/copied|selected/i.test(await page.locator('#toast').innerText()));
 await page.screenshot({path:path.join(output,'detail.png')});await page.press('body','Escape');check('Escape closes detail',!(await page.locator('#asset-dialog').evaluate(e=>e.open)));
 await page.fill('#search','');await page.selectOption('#status-filter','Failed');check('Missing assets included by failure filter',(await page.locator('#include-missing').isChecked()) && await page.locator('.asset-card').count()===40);
 await page.selectOption('#status-filter','all');await page.uncheck('#include-missing');
 await page.click('[data-surface="dark"]');check('Dark background',await page.locator('body').getAttribute('data-surface')==='dark');await page.uncheck('#checker-toggle');check('Checkerboard toggles',await page.locator('body').getAttribute('data-checker')==='false');
 await page.click('[data-view="shop"]');check('Selected shop preview exists',await page.locator('#selected-shop-item img').count()>0);
 await page.selectOption('#presentation-state','owned');check('Mock owned state visible',(await page.locator('#selected-shop-item').innerText()).toLowerCase().includes('owned'));
 await page.click('[data-shop-tab="Fashion"]');check('No invented fashion cards',await page.locator('[data-shop-item]').count()===0);
 await page.click('[data-shop-tab="Technology"]');await page.screenshot({path:path.join(output,'shop.png')});
 await page.click('[data-view="quality"]');check('118 failures retained',await page.evaluate(()=>NIHONGO_ASSETS.entries.filter(r=>r.failure).length)===118);
 await page.setViewportSize({width:375,height:812});await page.click('[data-view="shop"]');check('Mobile selected preview visible',await page.locator('#selected-shop-item').isVisible());
 check('Mobile has no horizontal page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'mobile-shop.png'),fullPage:true});
 await page.setViewportSize({width:768,height:1024});await page.click('[data-view="gallery"]');check('Tablet no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 check('No page errors or failed local requests',errors.length===0);
 fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({mode:'Headless Chrome, direct file://, no server',checks,loadedImages:loaded,errors},null,2));await browser.close();console.log(JSON.stringify({passed:checks.length,loadedImages:loaded}));
})().catch(e=>{console.error(e);process.exitCode=1});
